### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark-Script#16]
I started out fixing the issue with pasted in styles not saving, and ended up rewriting the script!

The rewrite is currently available in the [rewrite branch](https://github.com/StylishThemes/GitHub-Dark-Script/blob/rewrite/github-dark-script.user.js). Once everything checks out, I'll merge it into the master.

I tried to test it as thoroughly as I could. Please put it through the ringer!

Here are a few changes to note:
- jQuery dependency has been removed.
- Settings have reset - the script now saves `data` instead of each individual setting.
- Debug changes:
  - Enable debug - add `?debug=on` to URL.
  - Disable debug - add `?debug=off` to URL.
  - The change allows logging to continue when switching tabs.
- I'm trying to start using ES2015 more, but because you will need to load babel to make it work, I've limited the script to use implemented parts. I'm still learning, so feel free to do whatever!

**Comment by silverwind** [comment]
> jQuery dependency has been removed.

Good call, that ought to give it a bit more speed. If you still want some of the convenience of jQuery, you could try [bling.js](https://gist.github.com/paulirish/12fb951a8b893a454b32), or my [enhanced version](https://github.com/silverwind/squery).

> Debug changes

Another alternative could be to use Greasemonkey's built-in "User-Scripts Commands" menu.

> I'm trying to start using ES2015 more

With Safari Extenstions being unable to bypass GitHub's CSP, we only have to support Chrome and Firefox which should give us nearly 100% of ES2015, so no need for Babel.

**Comment by Mottie** [comment]
I tried using template literal placeholders, but Chrome didn't seem to like it. Maybe I did something wrong.

**Comment by Mottie** [comment]
Hmm, I've noticed that when I use the "Force update" button, after the page reloads the style doesn't apply. I see this error in the console

> Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src assets-cdn.github.com".

But if I reload the page using the browser button, everything is fine.

**Comment by silverwind** [comment]
>  I tried using template literal placeholders, but Chrome didn't seem to like it. Maybe I did something wrong.

They should definitely work in Chrome since at least a few months.

> Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script

Smells like a Tampermonkey bug. Did you check the box to circumvent CSP in the Tampermonkey options?

**Comment by silverwind** [comment]
Or you know, you could just drop the paste feature altogether.

Lately, I just push changes to the style's `master` and force-update in the script. If something doesn't work, I just force-push to `master` (yeah it's evil) to get rid of the commit.

Alternatively, you could set up a `dev` branch on the style and force-update from the raw branch URL on demand.

**Comment by Mottie** [comment]
Tampermonkey is set to add itself to the CSP and I like the paste feature.

**Comment by silverwind** [comment]
Hmm, can you narrow down that `unsafe-eval` error to a particular code line? If I recall correctly, the conditions for it to trigger can be pretty weird sometimes.

**Comment by silverwind** [comment]
Took a look at the rewrite. Good job eliminating the `ghd` object. Overall, I'm not a big fan of those `$variables` when they're not jQuery object, but I guess old habits die hard :laughing:

If I might suggest, with my "helper" library above, instead of 

``` js
let $files = $$('#files .file-actions'),
  indx = $files.length;

while (indx--) {
  let el = $files[indx];
  // do something with el
}
```

you could do 

``` js
$('#files .file-actions').forEach(el => {
  // do something with el
});
```

Sorry, just had to bring it up, feel free to ignore me :wink:

**Comment by Mottie** [comment]
Isn't using `while` faster than `forEach`?... Well, I guess it doesn't matter in this case.

I kinda like keeping the `$` in variables that are elements attached to the DOM.

And naw, I appreciate the suggestions! I did look at your library, I will probably end up copying the `on` code over; but I'm trying to catch up with my TV shows on my day off. :wink:

**Comment by silverwind** [comment]
Yeah, classic `for` and `while` are likely a tiny bit faster, but it won't matter unless you're iterating millions of elements. I exclusively use the array functions `forEach` (and `some`, `every` and the new favorite `find`) nowadays, they're just so convenient and easy to read!

**Comment by silverwind** [comment]
Still gotta work on that library, by the way. For one, I'd like to have `Node` methods on `NodeList` too, so one can use the same syntax for one or multiple elements. Probably need a `Proxy` or something for that.

**Comment by Mottie** [comment]
The script was tweaked again in https://github.com/StylishThemes/GitHub-Dark-Script/commit/e473ab96e196aed3b13c32fe8712499ebbbdd698 ... the `debug` setting is now set through the GM settings panel... and I removed _almost_ all the `$` from the variables :stuck_out_tongue:

**Comment by Mottie** [comment]
I'm not sure which is better, but I found that you can use [`Array.from(NodeList)`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from) instead of `NodeList.prototype.__proto__ = Array.prototype;`.

I don't know if you'd want to change that in your squery library, or not.

**Comment by Mottie** [comment]
The script appears to be stable, since I've been using it for a few weeks.
