### ISSUE TITLE
Build automation

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark-Script#2]
Ideally, I'd like to run `make patch` and have it (in addition to git tag and package.json) bump this version here too:

https://github.com/StylishThemes/GitHub-Dark-Script/blob/6c5059a66a52a1577f9a1273a039b2d62b524ef1/github-dark-script.user.js#L3

I'm thinking `sed` might be the way to go, but it won't be compatible with Windows of course.

**Comment by Mottie** [comment]
I think we can make a grunt build use it to do a string replace:

```
grunt major // increase major #
grunt minor // increase minor #
grunt patch // increase patch #
```

**Comment by silverwind** [comment]
I've been recently moving my projects off Grunt because of `grunt-shell` bugs and the complexity of the Gruntfile, so I think I'll keep the Makefile and do a simple `sed` to bump the version in the script.

I know this isn't really compatibly with Windows, but I can do all releasing I guess :)

**Comment by Mottie** [comment]
I have no idea how to create/use/modify a Makefile :disappointed: 

What about using Gulp? or npm?

**Comment by silverwind** [comment]
A Makefile is just a list of tasks in the form of shell-commands that can be triggered through the `make <task>` command. It's simple, fast and quite powerful. I'm not sure what's the best way to get `make` on Windows is. Personally, I'd just install Cygwin ;)

Also, great intro to `make` here: https://gist.github.com/isaacs/62a2d1825d04437c6f08

npm would work for simple shell commands, but I find it very messy if you want to create tasks that depend on others. Not sure about gulp, like Grunt, it's a layer of complexity I'd like to avoid.

**Comment by silverwind** [comment]
Another idea: Greasemonkey supports a `script.meta.js` file for update checks which only contains the metadata block, making update checks safe some traffic. I'll think about a way to extract the metadata block from the script for that purpose.

**Comment by Mottie** [comment]
Check out this answer on [Stackoverflow](http://stackoverflow.com/a/6028937/145346) about using Powershell in Windows: 

```
get-content somefile.txt | %{$_ -replace "expression","replace"}
```

**Comment by silverwind** [comment]
This is resolved with introduction of `ver`.
