### ISSUE TITLE
Darkened Google page when All of the link of the results from GitHub.

### ISSUE THREAD

**Issue by ibnuda** [StylishThemes/GitHub-Dark-Script#21]
I'm using GitHub-Dark-Script version 2.0.6 on GreaseMonkey, Firefox 64 47.0.1.
![why is it](https://cloud.githubusercontent.com/assets/8169908/17302136/025cf436-5845-11e6-886e-9d7edc81243e.PNG)

I couldn't repro it when I use Google Chrome + TamperMonkey.

**Comment by Mottie** [comment]
Hi @ibnuda!

Odd, I'm not seeing the same problem

![2016-08-01 12_23_12-fsharp gui site_http___github com - google search](https://cloud.githubusercontent.com/assets/136959/17302639/cca40c2e-57e2-11e6-9c11-7161fd2c935b.png)

**Comment by silverwind** [comment]
That shouldn't happen unless you included Google manually in the script settings. Anything in these boxes maybe? 

![](https://cloud.githubusercontent.com/assets/115237/17302883/8e288eac-581e-11e6-9834-0001a65d473c.png)

**Comment by Mottie** [comment]
Oops, I shared a screenshot of Chrome... it's pretty much the same as what I see in Firefox.

**Comment by silverwind** [comment]
Is it only happening with `site:http://github.com` searches? Post your google URL when it happens.

**Comment by ibnuda** [comment]
Google URL when the posted picture happen : https://www.google.co.id/search?q=fsharp+gui+site:http://github.com&hl=id&biw=1192&bih=677&site=webhp&ei=j5SgV9PVA4LSjwOlsK7ACw&start=0&sa=N

Preferences : 
![user script preferences](https://cloud.githubusercontent.com/assets/8169908/17328695/5854fbaa-58e9-11e6-92e0-19ab7bb6fdb9.PNG)

**Comment by Mottie** [comment]
Ok, thanks! That helped solve the problem!

**Comment by Mottie** [comment]
Please update the script.
