### ISSUE TITLE
Not working with AdGuard

### ISSUE THREAD

**Issue by Bluscream** [StylishThemes/GitHub-Dark-Script#22]
I tried to use the script version of Github Dark with AdGuard but it doesn't work.

`Uncaught TypeError: Cannot create property 'lastTheme' on string '[object Object]'`
![image](https://cloud.githubusercontent.com/assets/3318223/19628655/51ee87e4-9963-11e6-8915-1b7f5011838d.png)
![image](https://cloud.githubusercontent.com/assets/3318223/19628659/5bd76a5a-9963-11e6-9946-e09dc5be82c2.png)

![image](https://cloud.githubusercontent.com/assets/3318223/19628661/668a729e-9963-11e6-9a1a-fde307239b96.png)

The browser im trying it with is Opera btw.
![image](https://cloud.githubusercontent.com/assets/3318223/19628689/d7c61b2a-9963-11e6-9cb1-bdb3decaac21.png)

**Comment by Bluscream** [comment]
BTW. The userstyles.org JS version works just fine.
![image](https://cloud.githubusercontent.com/assets/3318223/19628742/df10a700-9964-11e6-80a2-25559fbaaab6.png)

**Comment by silverwind** [comment]
What kind of userscript engine is that? Can you insert these two lines before the error code, and show what's logged to the console?

```
console.log(GM_info);
console.log(JSON.stringify(data));
```

**Comment by Bluscream** [comment]
`{script: Object, scriptMetaStr: "", scriptWillUpdate: true, version: "0.9.16", uuid: "uuid"}`
`ReferenceError: data is not defined(…)`

![image](https://cloud.githubusercontent.com/assets/3318223/19629302/20e0e39a-9972-11e6-85b2-cc6b0eaea082.png)
@silverwind

**Comment by silverwind** [comment]
Hmm, for all I know this userscript engine isn't properly implementing the [`GM_getValue`](https://wiki.greasespot.net/GM_getValue). Maybe we can work around. Why not just install Tampermonkey, by the way?

**Comment by Bluscream** [comment]
Cause this way it works with every application that displays websites computerwide.

**Comment by silverwind** [comment]
Ah, I see. Do you have the issue in all browsers by the way, or is it just Opera?

**Comment by Bluscream** [comment]
I can test it in some others if you want me to :)

**Comment by silverwind** [comment]
Might not be necessary, I have a strong suspicion on what's wrong. Try this version:

https://github.com/StylishThemes/GitHub-Dark-Script/raw/json-gm-data/github-dark-script.user.js

**Comment by Bluscream** [comment]
The skin itself seems to work
![image](https://cloud.githubusercontent.com/assets/3318223/19630498/eb0b0c4a-998b-11e6-8570-0f6ef54b1ffc.png)

P.S. I restarted the browser and it seems like the css was only cached :(
![image](https://cloud.githubusercontent.com/assets/3318223/19630514/5e724798-998c-11e6-97f5-ab8287e24bc6.png)

**Comment by Bluscream** [comment]
I revert everything. Cleared browser cache and voilá 
![image](https://cloud.githubusercontent.com/assets/3318223/19630542/ed3a35bc-998c-11e6-9a34-0aeeaedcf1b8.png)

**Comment by Bluscream** [comment]
BTW: AAK says it's greasemonkey: 
![image](https://cloud.githubusercontent.com/assets/3318223/19631090/566b6eca-9997-11e6-9003-0c463ad8618e.png)

**Comment by silverwind** [comment]
It's looks like its something proprietary, https://github.com/AdguardTeam/AdguardForWindows/issues/1218 describes the supported APIs.
