### ISSUE TITLE
Compatibility issue with "Github file list beautifier"

### ISSUE THREAD

**Issue by Bluscream** [StylishThemes/GitHub-Dark-Script#23]
![image](https://cloud.githubusercontent.com/assets/3318223/19758538/d40988ba-9c28-11e6-9208-fd131dae4706.png)

It seems like the dark css is breaking compatibility with [Github file list beautifier](https://greasyfork.org/en/scripts/5982-github-file-list-beautifier).

![image](https://cloud.githubusercontent.com/assets/3318223/19758571/f86708b8-9c28-11e6-99f2-4199f01481a6.png)

![image](https://cloud.githubusercontent.com/assets/3318223/19758579/ffd87776-9c28-11e6-902f-237a385e9de6.png)

It would be nice if you can atleast tell me to fix it. Do i just have to add `!important;` modifier to their css?

**Comment by silverwind** [comment]
Try adding `!important` on [line 134](https://greasyfork.org/en/scripts/5982-github-file-list-beautifier/code#n134), before the `}`.

**Comment by Bluscream** [comment]
Didn't work. It's already `color:#4183C4 !important` in `.ghd-style`.

It does work with unticking the rule in the inspector:
![image](https://cloud.githubusercontent.com/assets/3318223/19777134/25a708d4-9c77-11e6-8e27-c6ef6dc1e003.png)

**Comment by silverwind** [comment]
Ah, you need even more specificity (we can't really reduce it on our side), try this:

``` js
var color = 'html a[file-type="' + type + '"] { color: hsl(' +
  (hash%360) + ',' +
  (hash*config.colorSeed2%50 + 50 |0) + '%,' +
  (hash*config.colorSeed3%15 + 25 |0) + '%) !important }';
```

**Comment by Bluscream** [comment]
Works fine with this fix. Thanks ♥
