### ISSUE TITLE
The hovered item in dropdown menus is hard to read

### ISSUE THREAD

**Issue by HatScripts** [StylishThemes/GitHub-Dark-Script#24]
The hovered item (`.dropdown-item`) in dropdown menus (`.select-menu-button`) is quite hard to read. I can probably submit a pull request later on as this can be slightly annoying.

Seems like this would be all that's needed:
```
.dropdown-item:hover {
        background: #222 !important;
}
```

![watch dropdown](https://cloud.githubusercontent.com/assets/5691865/20581962/aa064bb6-b230-11e6-9dbc-a30c20c2e417.png)
![filter dropdown](https://cloud.githubusercontent.com/assets/5691865/20581964/aa0b6d12-b230-11e6-8d4d-2bde3aa954e0.png)
![avatar dropdown](https://cloud.githubusercontent.com/assets/5691865/20581963/aa08ec5e-b230-11e6-83cf-6799c7364f60.png)

**Comment by Mottie** [comment]
Hi @HatScripts!

I'm not seeing this same problem shown in the screenshots.

Please use the "Force Update Style" to ensure you have the most up to date style - currently v1.16.10. If you do, then please check to see if there are any other installed styles that might be interfering.

Anyway, the watch and issue filter dropdowns actually have a class name of "select-menu-item" instead of "dropdown-item".

**Comment by Bluscream** [comment]
![image](https://cloud.githubusercontent.com/assets/3318223/20584121/020fef1a-b1f0-11e6-840a-73fda4185ac2.png)

**Comment by HatScripts** [comment]
@Mottie Wow, the solution was a frustratingly simple one, but I only realised it after typing all this up:

> * I disabled all extensions except for Tampermonkey
> * I made sure this was the only userscript enabled for the github.com domain
> * I made sure I've got the latest version of the userscript and CSS, and I do, v2.0.16 and v1.16.10 respectively
> * I cleared my cookies and cache
> 
> I've still got the same issue despite all this. Hmm, I'm using Opera if that helps at all.
> 
> ![2016-11-25 00 06 43 stylishthemesgithub-dark-script_github_dark_as_a](https://cloud.githubusercontent.com/assets/5691865/20599675/8070e19e-b2a3-11e6-8dca-f13c24eecd29.png)
> 
> It also occurs with the @username autocomplete dropdown.
> ![2016-11-25 00 13 05 the_hovered_item_in_dropdown_menus_is_hard_to_read](https://cloud.githubusercontent.com/assets/5691865/20599772/18ca211c-b2a4-11e6-9baa-d2d940330a9c.png)
> ![2016-11-25 00 18 18 the_hovered_item_in_dropdown_menus_is_hard_to_read](https://cloud.githubusercontent.com/assets/5691865/20599877/b36be9d0-b2a4-11e6-83c7-61ae65f00b09.png)
> Both `color: #efefef !important;` and `background: #FFFFFF !important;` for `.suggester li` are found within the `<style class=".ghd-style">...</style>` stylesheet for me.

...

My highlight colour was set to white. I am dumb. 😅
![2016-11-25 00 33 50 the_hovered_item_in_dropdown_menus_is_hard_to_read](https://cloud.githubusercontent.com/assets/5691865/20600281/e93ca372-b2a6-11e6-8432-0a4c00a06767.png)

**Comment by Mottie** [comment]
We all have bad days!

<img title=":_tuzki_teehee:" src="https://cloud.githubusercontent.com/assets/136959/13203716/665ac5c2-d883-11e5-87ef-bbb0be4e1d81.gif">
