### ISSUE TITLE
White "Contribution Activity" 'hots'

### ISSUE THREAD

**Issue by Bluscream** [StylishThemes/GitHub-Dark-Script#25]
![image](https://cloud.githubusercontent.com/assets/3318223/20733717/42cb032e-b695-11e6-8454-a973db0dd459.png)

![image](https://cloud.githubusercontent.com/assets/3318223/20733794/aa0510de-b695-11e6-8a7a-972b71ca9cda.png)

**Comment by Mottie** [comment]
Hi @Bluscream!

Odd, I see you're up-to-date, but I'm not seeing that issue. Would you please share a link to that timeline.

**Comment by Bluscream** [comment]
Sure, https://github.com/Bluscream (I'm already building the PR for the fix, give me 10 minutes :D

**Comment by Mottie** [comment]
Well before you submit a PR, please make sure that there isn't a Stylish theme interfering. And use the "Force Update" to make sure everything is definitely up-to-date.

**Comment by Mottie** [comment]
I see it currently defined as "bg-white" on [line 919](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L919).

```css
/* .... */ .bg-white, /* ... */ {
  background: #181818 !important;
}
```

**Comment by Bluscream** [comment]
![image](https://cloud.githubusercontent.com/assets/3318223/20734252/8dab0a8a-b698-11e6-8089-7c04c814294c.png)

**Comment by Mottie** [comment]
Ahhh nevermind, I see it now... GitHub must have just updated.. great, they are using a lot of `!important` flags now.

**Comment by Bluscream** [comment]
Yeah, i wonder why. Maybe they have own old css that they need to overwrite? ...

**Comment by Mottie** [comment]
So the easiest fix would be to slap an body in front of it: `body .bg-white`... would you please do that to `.border-gray-dark` definition as well?

**Comment by Bluscream** [comment]
Sure thing :)

**Comment by Mottie** [comment]
@silverwind UGH!.... 

* https://github.com/primer/primer-utilities/blob/master/lib/colors.scss
* https://github.com/primer/primer-utilities/blob/master/lib/borders.scss

**Comment by silverwind** [comment]
Hmm maybe there's a better solution than to prepend `body` to each of those selectors. For two same-weight rules, the latter defined rule should win. We already append our `<style>` to the end of `<head>`, so I'm unsure on why you even see the issue. Keep in mind, we cannot append to `<body>` because it's not parsed by the time our script loads.
