### ISSUE TITLE
Disable the style?

### ISSUE THREAD

**Issue by FranklinYu** [StylishThemes/GitHub-Dark-Script#27]
Can I permanently disable the style while using the plugin (so the code-wrapping and monospaced textarea still works)? Currently when I click to a new page, there is a "white flash" before the CSS takes place. I would like to use this plugin while keeping CSS in Stylish (to get rid of the white flash). The checkbox of "Enable GitHub Dark" doesn't seem to persist across pages, or across refresh.

**Comment by Mottie** [comment]
Hi @franklinyu!

If you look at the main readme under [Toggles](https://github.com/StylishThemes/GitHub-Dark-Script#toggles), you'll see links to install each userscript separately. There are three:

* Code Wrap toggle
* Comment monospace toggle
* Diff file toggle

**Comment by FranklinYu** [comment]
So the checkbox doesn't persist *by design*? I thought it's a bug. Thanks then.

**Comment by Mottie** [comment]
Sorry, which checkbox? Do you mean the GitHub-Dark enabled checkbox? Then yes, that is only meant to temporarily disable the style for comparison.

I guess it would make more sense to have it persist; either way, if you aren't using the GitHub-dark portion of the userscript, then this main script is essentially code bloat.
