### ISSUE TITLE
Labels assigning dropdown mis-aligned

### ISSUE THREAD

**Issue by devkhan** [StylishThemes/GitHub-Dark-Script#28]
While trying to add an issue:

![image](https://cloud.githubusercontent.com/assets/8049092/23201104/f5b36918-f8fd-11e6-9bf9-cbd2ed3e3a87.png)

**Comment by silverwind** [comment]
I may be blind, but what part of that screenshot is misaligned exactly?

**Comment by devkhan** [comment]
Both for comparison:

![image](https://cloud.githubusercontent.com/assets/8049092/23293031/a9af0544-fa89-11e6-9d87-20df5f67f10b.png)
![image](https://cloud.githubusercontent.com/assets/8049092/23293040/b840c66a-fa89-11e6-9139-5baa6eb315d8.png)

It's just a nit-pick, but I thought I might report this anyway.

**Comment by silverwind** [comment]
Ah, I see the sidebar is moved quite a bit to the right, which is very weird. What browser are you using and can you link me to the issue where it's happening?

**Comment by devkhan** [comment]
Version info:

```
Google Chrome  56.0.2924.87 (Official Build) (64-bit)
Revision  0e9a9a6f3676ae439b78cd9b3f62b4193c3ac7d5-refs/branch-heads/2924@{#895}
OS  Mac OS X 
JavaScript  V8 5.6.326.50
Flash  24.0.0.221 /Users/devkhan/Library/Application Support/Google/Chrome/PepperFlash/24.0.0.221/PepperFlashPlayer.plugin
User Agent  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
```

In general, I can see this on any issue, so it's not a repo/issue specific issue.

**Comment by Mottie** [comment]
This doesn't appear to be a Windows + Chrome problem. Is it still an issue for you in Chrome 57?

**Comment by devkhan** [comment]
Thanks. Fixed in Chrome v57.
