### ISSUE TITLE
Does not apply to the gitter.im (part of github)

### ISSUE THREAD

**Issue by CollinChaffin** [StylishThemes/GitHub-Dark-Script#29]
Probably a feature request I love this theme but it does not seem to apply to the gitter.im github chat section and would be very consistent if it carried onto that section of the site as well.

**Comment by Bluscream** [comment]
Gitter is a third party website and in no way affiliated with Github but you can check out dark userstyles for gitter.im

**Comment by CollinChaffin** [comment]
Ahh then I apologize it's so integrated into every git page these days I literally thought that it was a part of Github!
