### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark-Script#3]
@Mottie I see your style for whitespace (particulary the function argument spacing) is quite different from mine, which is not a bad thing but it will lead to inconsistencies.

I placed an `.eslintrc` which is meant to enforce a particular style, which you can check by first installing ESLint (`npm i -g eslint`) and then running `eslint *.js`. As you're so far the prime contributor, I'd suggest you adapt the rules in `.eslintrc` to suit you needs. I'm using a plugin for SublimeText which highlights any linter errors, so it's easy for me to adapt once the rules are fixed :)

**Comment by Mottie** [comment]
No worries, I'm adaptable :grin: 

And thanks for the instructions... I never had eslint installed LOL

**Comment by silverwind** [comment]
Very nice of you :+1:
