### ISSUE TITLE
Tooltips at screen top are hidden/overlapped by top nav bar

### ISSUE THREAD

**Issue by CollinChaffin** [StylishThemes/GitHub-Dark-Script#30]
The addon/referenced Github addon themes include one to expand the top nav bar etc. and I know this is minor but just wanted to point out that the tooltips for the top right elements like WATCH/STAR/FORK when theme is enabled are hidden under the navbar as shown in these screenshots below.  I am not sure if it is possible, but a really nice change just to ensure if in the future Github were to add other functions and corresponding tooltips would be just to MOVE those tooltips down UNDER the corresponding elements.  The dumb placement of them above elements so close to the top of the screen of course were not even made by this theme but by the original site dev, but they got away with it (barely) only because the original site didn't have quite the height of the nav bar with all the functionality being added here.  :_bow: 

FORK tooltip (the tiny bit of white if you look):
https://1drv.ms/i/s!AhSqjTYUuHPKgcNbmBCOm-wDiU936w

STAR tooltip (the tiny bit of white if you look):
https://1drv.ms/i/s!AhSqjTYUuHPKgcNaLEhGWHrofnpBQg

Again not even sure this is considered a bug in this theme but really a SITE bug that becomes a problem only when this theme is applied (and not a major one).

**Comment by Mottie** [comment]
Hi @CollinChaffin!

GitHub has removed the tooltips from the star and fork buttons. So, it looks like the problem is in the `github-script-make-tooltips.user.js` code. It is currently set to make all tooltips point up, I'll update the code to make those point down... thanks for letting us know!

**Comment by CollinChaffin** [comment]
Hey thanks for getting on this.  Wanted to let you know right away that whatever just got changed in the cooresponding "Github make tooltips" I assume kicked off from this because it just started throwing this error immediately after it just updated that script and must now have a critical code error screenshot below I will also see if there is even a way to open a separate issue somewhere specific to that script but it is a critical enough error that it actually prevents loading:

https://1drv.ms/i/s!AhSqjTYUuHPKgcNd7MCeZPS4FTJSFg
