### ISSUE TITLE
Make tooltips userscript error after last update to move tooltips to bottom

### ISSUE THREAD

**Issue by CollinChaffin** [StylishThemes/GitHub-Dark-Script#31]
Left comment in other closed issue but the recent update to the make tooltips script (I believe to move tooltips to bottom) has a critical error that prevents all loading.  Screenshot below looks like something is calling to a length property with a null but I have not been able to try to debug thought might be faster for you since you know what you changed etc.

Screenshot:  https://1drv.ms/i/s!AhSqjTYUuHPKgcNd7MCeZPS4FTJSFg

Thanks again for getting on that one so quickly!

**Comment by Mottie** [comment]
Hi @CollinChaffin!

Sorry for the trouble. Odd that you're getting an error, because I did test it. Anyway, I'll have a fix available ASAP!

**Comment by CollinChaffin** [comment]
I can confirm it is fixed and looks perfect!

https://1drv.ms/i/s!AhSqjTYUuHPKgcNjIruvh9cSd5e0lw

Thanks!
