### ISSUE TITLE
Custom sub-themes for Dark?

### ISSUE THREAD

**Issue by rmenessec** [StylishThemes/GitHub-Dark-Script#33]
I was very excited to see Monokai listed, before reality kicked in, and I realized it was a syntax theme rather than a whole-site theme.

I realize this might be a lot of extra work, but it would be great to see some additional whole-site styles available at some point.

Thanks for the work you've put into this! I'm loving it.

**Comment by Mottie** [comment]
Hi @rmenessec!

Interesting idea, but it looks like someone already did it: https://github.com/alphapapa/solarized-everything-css
