### ISSUE TITLE
OpenUserJS is outdated

### ISSUE THREAD

**Issue by ShalokShalom** [StylishThemes/GitHub-Dark-Script#35]
If the last 2 minor releases contain some security fixes, i suggest to remove the OpenUserJS link, until they update their version. Its already reported on their side.

**Comment by Mottie** [comment]
Hi @ShalokShalom!

No, they were just minor edits... I was going to hold off on a new release until we resolved whatever errors you were encountering.

**Comment by ShalokShalom** [comment]
I dont know, if they are issues in your script. Currently runs all fine, i cant reproduce, while i was able to do that before within some reloads. Now all fine since hours.

**Comment by Mottie** [comment]
The dependencies were updated, which is only eslint. And the second update was removing an unused variable. I don't think they were causing any issues. So can we close this issue now?
