### ISSUE TITLE
Child Teams Collapsible View Not Being Styled

### ISSUE THREAD

**Issue by quantumpacket** [StylishThemes/GitHub-Dark-Script#36]
You can add child teams to an organization team. Under the "Teams" tab there is an overview of all the parent teams, with a collapsible view of their child teams. That is not being styled.

Please note a child team can have its own child team, and so on (not sure if there is a hard limit). So the collapsible view gets nested as more child teams are added recursively.

Release: v2.2.4

![screenshot_2017-06-28_01-02-10](https://user-images.githubusercontent.com/8516784/27621383-7005ac6e-5b9e-11e7-84ab-8e556337034a.png)

**Comment by Mottie** [comment]
Hi @quantumpacket!

Thanks for letting us know!
