### ISSUE TITLE
Firefox Support for either Tampermonkey or Violentmonkey?

### ISSUE THREAD

**Issue by crkellen** [StylishThemes/GitHub-Dark-Script#39]
So I used this while using Greasemonkey, but I'd like to move away from using Greasemonkey as it isn't e10s compatible. I'm currently using Violentmonkey, but as expected, the script doesn't function.

Is there a fix for this, will support be added later, as eventually with Firefox 57, e10s add-ons will be the only option.

**Comment by Mottie** [comment]
Hi @crkellen!

We are providing a userscript which isn't browser specific. Once Violentmonkey and Tampermonkey start working in FF v57, then we hope the userscript will work. Except...

If you look at issue #13, you'll see there is an issue with Tampermonkey and GitHub's Content Security Policy (CSP). This appears to be the same problem with Violentmonkey:

> Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://assets-cdn.github.com”). Source: (function s(t,n,e,r){t.initialize(n,e,r)....

There really isn't anything we can modify in this script to solve this issue. I think it is up to the browser.

**Comment by crkellen** [comment]
Well dang. Thanks for letting me know! You can choose to close this if you want.
