### ISSUE TITLE
Code wrapping

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark-Script#4]
Need to fix code wrap button:
## Okay here

``` js
longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong
```

```
longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong
```
## Missing or misaligned:
- See [this readme](https://github.com/gjtorikian/html-proofer/blob/master/README.md).
- Wrapped:
  
  ```
  longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong
  ```
- Inline: `longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong`
- Using space indention
  
  ```
  longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong
  ```

**Comment by Mottie** [comment]
Also, update to allow individual block toggling.

**Comment by silverwind** [comment]
Regarding inline style with `!important`, it looks to be possible:

https://jsfiddle.net/silverwind/snmcetmk/

**Comment by Mottie** [comment]
Ok, I think I got most of this working...

**Comment by silverwind** [comment]
Nice work. The inline one probably isn't necessary, unwrapping it would break the layout I assume. Example 3 and 5 look to be working once you tap the wrap button twice.

**Comment by silverwind** [comment]
Pushed https://github.com/StylishThemes/GitHub-Dark/commit/1293f4302685f3b19b6cbd48af53849fc82f4e0c so boxes that don't directly descend `.markdown-body` are properly wrapped.

**Comment by silverwind** [comment]
I assume these last two cases should work now after https://github.com/StylishThemes/GitHub-Dark-Script/commit/072f603463fc37ddb9c97731399c2e60b2d33f27, but for some reason my CSS won't update even after I force it, gotta investigate later.

**Comment by Mottie** [comment]
Ok, last issue...

When switching from this page - https://github.com/gjtorikian/html-proofer/blob/master/README.md - to the repo root that shows the same readme, the icon wrappers are not being applied because GitHub uses [pjax](https://github.com/defunkt/jquery-pjax) to load content into the main container.

The problem is I can't get the pjax events to work (e.g. `pjax:complete`, `pjax:success`, etc). They just don't seem to fire.

[Octotree](https://github.com/buunguyen/octotree/blob/master/src/adapters/github.js#L51) instead uses a `MutationObserver` to detect the change.

So, my question is, how far should I go to appease my OCD? LOL

**Comment by Mottie** [comment]
I ended up not needing to use a `MutationObserver`, but I did have to access the jQuery version outside of the sandbox.

I also added a copy of the `ghd` object to the main window to make it easier to debug, access it like this:

``` js
console.log($('#ghd-settings').data('ghd'));
```

Not that we really called this an alpha version, I do think it's stable enough to call it  beta. What do you guys think?

**Comment by silverwind** [comment]
Good job, I also like to avoid MutationObservers because how finicky they can be to get right. Care to explain why accessing the pages's jQuery is needed? Are those `pjax:complete` events custom jQuery events (i.e. not DOM events?).

Also, I'm fine with calling it beta now. It's already pretty stable :+1:

**Comment by Mottie** [comment]
GitHub uses [pjax](https://github.com/defunkt/jquery-pjax) to load content on the page, but I found it uses three different containers. The `pjax:complete` event is triggered by that plugin using the page jQuery so that why I had to use the `unsafeWindow.jQuery`. Sadly, I found a problem.

I just updated another [userscript of mine](https://github.com/Mottie/Github-show-repo-issues) and found that using `unsafeWindow` doesn't work in Firefox. So, I had to rewrite it and use MutationObservers.

Can you verify if this GitHub-Dark script is working for you? I use Firefox as a test platform and try not to log into GitHub LOL.
