### ISSUE TITLE
Tampers structurizr.com website sourcing from gists by mistake

### ISSUE THREAD

**Issue by DKroot** [StylishThemes/GitHub-Dark-Script#40]
structurizr.com is a web-based diagram tool that allow to source diagram from gists. For example:

https://structurizr.com/express?src=https://gist.githubusercontent.com/simonbrowndotje/ee1c266dfd123a4d5660a8aa19da9e61/raw/21bed60ca5551f22f273aee10efedb1c57c7dd71/gistfile1.txt

GitHub Dark Script tampers structurizr.com diagram in this case, which is a bug.

**Comment by Mottie** [comment]
Hi @DKroot!

Thanks for reporting this issue. I'll have it fixed shortly.
