### ISSUE TITLE
Tampermonkey option do not open firefox 56 b2 64bit

### ISSUE THREAD

**Issue by toraias** [StylishThemes/GitHub-Dark-Script#41]
Tampermonkey stopped working: no ptions window visible as pop up or opening from addons page:

Content Security Policy: Ustawienia strony zablokowały wczytanie zasobu „self” („script-src moz-extension://72f98454-59f7-48a1-b432-1c469d26409e”). Source: onsubmit attribute on DIV element. options.html
Content Security Policy: Ustawienia strony zablokowały wczytanie zasobu „self” („script-src moz-extension://72f98454-59f7-48a1-b432-1c469d26409e”). Source: onchange attribute on DIV element. options.html
Content Security Policy: Ustawienia strony zablokowały wczytanie zasobu „self” („script-src moz-extension://72f98454-59f7-48a1-b432-1c469d26409e”). Source: onfocusin attribute on DIV element. options.html
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. ExtensionCommon.jsm:304
	withLastError resource://gre/modules/ExtensionCommon.jsm:304:9
	wrapPromise/< resource://gre/modules/ExtensionCommon.jsm:357:11
	getRaw moz-extension://72f98454-59f7-48a1-b432-1c469d26409e/registry.js:4:159
	addStyle moz-extension://72f98454-59f7-48a1-b432-1c469d26409e/layout/default/layout_helper.js:8:335
	<anonimowa> moz-extension://72f98454-59f7-48a1-b432-1c469d26409e/layout/default/options.js:3:315
	render/< moz-extension://72f98454-59f7-48a1-b432-1c469d26409e/layout.js:4:131
	render/< moz-extension://72f98454-59f7-48a1-b432-1c469d26409e/layout.js:4:114
	render moz-extension://72f98454-59f7-48a1-b432-1c469d26409e/layout.js:4:77
	<anonimowa> moz-extension://72f98454-59f7-48a1-b432-1c469d26409e/layout/default/options.js:3:294
	m moz-extension://72f98454-59f7-48a1-b432-1c469d26409e/registry.js:1:229
	g/</< moz-extension://72f98454-59f7-48a1-b432-1c469d26409e/registry.js:1:339
	d moz-extension://72f98454-59f7-48a1-b432-1c469d26409e/registry.js:4:380
Błąd przetwarzania XML: nieprawidłowo sformowany
Obszar: moz-extension://72f98454-59f7-48a1-b432-1c469d26409e/layout/default/style.css
Numer wiersza: 1, kolumna 1:  style.css:1:1
a is undefined  options.js:154
	oa/< moz-extension://72f98454-59f7-48a1-b432-1c469d26409e/layout/default/options.js:154:117
	runSafeSyncWithoutClone resource://gre/modules/ExtensionUtils.jsm:61:14
	runSafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:174:38
	runSafeWithoutClone self-hosted:949:17
	wrapPromise/< resource://gre/modules/ExtensionCommon.jsm:353:13

**Comment by silverwind** [comment]
Maybe it's https://github.com/Tampermonkey/tampermonkey/issues/418? Try the beta version of Tampermonkey.

**Comment by Mottie** [comment]
I'm going to close this issue since a new version of Tampermonkey just came out (beta version) and it's been 9 months since this issue has been opened with no feedback.
