### ISSUE TITLE
Textareas have a blue background when focused

### ISSUE THREAD

**Issue by IceCreamYou** [StylishThemes/GitHub-Dark-Script#42]
Here's what it looks like to me when I create a new issue or write a comment:

![image](https://user-images.githubusercontent.com/203177/32077555-a64ff798-ba58-11e7-9c21-bf62aac71dce.png)

This started happening a few days ago. Previously the background was dark gray, which is much preferable.

Edit: I have the Refined Github extension enabled but I have verified that the problem still occurs with the extension disabled. I'm in Chrome 62.0.3202.62

**Comment by Mottie** [comment]
Hi @IceCreamYou!

Yep, sorry, I pushed that commit and fixed in it within 30 minutes. Use the force update to grab the lastest style.

**Comment by IceCreamYou** [comment]
Oh, I had tried to update the userscript unsuccessfully, but I just read more documentation and found the "force update styles" in the settings and that worked. Thanks!
