### ISSUE TITLE
Greasemonkey 4 compat

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark-Script#43]
Currently the script is incompatible with GM4 which introduces a bunch of new async APIs in place of the old `GM_` APIs which are still implemented in Tampermonkey and other engines. We probably want to use the polyfill mentioned.

https://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html

**Comment by Mottie** [comment]
I think we can add the polyfill and figure out how to get all versions to work with async/await. I need some time to catch up with all the issues/email and I'll work on it; if you haven't already beaten me to it 😉.
