### ISSUE TITLE
Problems on the projects page.

### ISSUE THREAD

**Issue by jarrodls** [StylishThemes/GitHub-Dark-Script#44]

**Comment by Mottie** [comment]
Hi @JarrodS846!

I'm guessing you can't move project cards? It's a known issue, and I believe an issue with Tampermonkey - see https://github.com/StylishThemes/GitHub-Dark/issues/581.

**Comment by jarrodls** [comment]
Yeah sorry, stuffed up this issue. Wasn't sure if this was an issue with the script or CSS yeah, cant move cards while the script is activate, have to disable it, reload page, move stuff then re-enable it.  Only mildly annoying.

Also noticed that I can't open the script menu (from the dropdown) while on the page. The `GitHub Dark Settings` option. This is on an org page as well so `github.com/orgs/{org}/projects/{project}`. Seems to work on normal user projects though?

**Comment by Mottie** [comment]
I can't duplicate the dropdown issue, at least from [this page](https://github.com/StylishThemes/GitHub-Dark/projects/1). Are you seeing any errors in the developers console?

**Comment by jarrodls** [comment]
Nope, no errors just this in the console.
![image](https://user-images.githubusercontent.com/22313733/35834257-000e536c-0b29-11e8-861e-3295ba8bb772.png)

Seems to only be projects under Organizations so they aren't actual repos. I can't find any examples of public organizations that have projects however. For context, this is an example of an organization with projects in an image.

![image](https://user-images.githubusercontent.com/22313733/35834387-9a3bc21c-0b29-11e8-9215-755264fb4c37.png)

**Comment by Mottie** [comment]
Ok, found that problem and fixed it - https://github.com/orgs/StylishThemes/projects/1
