### ISSUE TITLE
Can't save settings in firefox

### ISSUE THREAD

**Issue by tflori** [StylishThemes/GitHub-Dark-Script#45]
I'm using Firefox 58.0.2 with Tampermonkey 4.6.5709 and whenever I change something (font, background image, code theme) it does not change, even when I click on force update. After reloading the changes are set to default.

In console the object printed after "Retrieved stored values" does not reflect my changes too (guess that's the main problem). When I close github dark settings I get the following error:

```
Updating user settings
TypeError: picker is undefined
TypeError: picker is undefined
```

**Comment by DanaMW** [comment]
When this happens to me it always ends up being an error in one of the scripts. I would if you go to scripts source and reload all the ones you cant edit then  recheck the ones you can edit and maybe you will resolve it like i always seem to Hope that helps.. My gihub dark had to be reloaded once also.

**Comment by tflori** [comment]
you mean externals like: `https://greasyfork.org/scripts/15563-jscolor/code/jscolor.js?version=106439` ?

**Comment by tflori** [comment]
both sources from greasyfork are not available.. and when I remove the version specification it works.

So maybe you should remove the version specification or at least update it... (currently I can't update without breaking it)

**Comment by DanaMW** [comment]
Yes. Those and the ones in Stylus too. It worked for me. I have found that if I try to remote save a script with errors sometimes another different script can slightly corrupt. And cause weird errors, After wasting many hours i go straight to hunting through them all for linting errors

**Comment by DanaMW** [comment]
As was pointed out to me when there is an error things become seen as global causing weird errors.

**Comment by DanaMW** [comment]
Not sure that is your issue and I am probably wrong but that is where i look first now.

**Comment by Mottie** [comment]
Hi @tflori!

This appears to be an issue with GreasyFork. The [jscolor library](https://greasyfork.org/en/scripts/15563-jscolor/code) stored there shows the same url &ndash; https://greasyfork.org/scripts/15563-jscolor/code/jscolor.js?version=106439 &ndash; but it's not providing any code.

I opened an issue - https://github.com/JasonBarnabe/greasyfork/issues/539.

And thanks @DanaMW for helping! 😸

**Comment by tflori** [comment]
ok, thx
