### ISSUE TITLE
Project Card Drag and Drop bug

### ISSUE THREAD

**Issue by SweetJake** [StylishThemes/GitHub-Dark-Script#46]
When running dark script the drag and drop feature that enables me to drag a card from one column in a project to another doesn't work while the script is enabled.

Chrome Version: Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by Mottie** [comment]
Hi @SweetJake!

This is actually an issue with TamperMonkey (assuming you're using it).

See https://github.com/StylishThemes/GitHub-Dark/issues/581 &amp; https://github.com/Mottie/GitHub-userscripts/issues/36.

**Comment by SweetJake** [comment]
Yup that is exactly it. Thanks

**Comment by Mottie** [comment]
It looks like Tampermonkey v4.6 is now available... closing this issue.
