### ISSUE TITLE
Updating/Reset bugs

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark-Script#5]
Found these issues:

1) Force update doesn't seem to update reliably when the version number is unchanged, the latest change in the stylesheet regarding wrapping doesn't get applied.

2) When resetting all settings, it seems the theme's css is only applied on the second page reload.

**Comment by Mottie** [comment]
1) Hmm, maybe we can skip the package.json check if the stored version is zero.

2) I'll have to look into that later... busy day today!

**Comment by silverwind** [comment]
Found the cause for No. 1: The URL is only fetching the released version on the gh-pages branch. I'll change it to fetch from master now, we might want to include an option to fetch pre-release versions later.

**Comment by silverwind** [comment]
Added an option to use the dev version in https://github.com/StylishThemes/GitHub-Dark-Script/commit/14ca93f05e03c90d58e60cf1acdde33cdd815319.

The options box is getting quite big, I think something like `max-height: 90vh; overflow-y: scroll` may be necessary on small displays :)

**Comment by Mottie** [comment]
Ok, everything in this issue should now be resolved. Please test it out and make sure :grin:

**Comment by Mottie** [comment]
When you added the `dev` option, did you want that to be saved? Or have it reset after page reload?

**Comment by silverwind** [comment]
Should be saved, so users get updates immediately.

**Comment by Mottie** [comment]
Maybe we should always get the master branch style on forced updates?

**Comment by silverwind** [comment]
Hmm, that could work too. We could remove the options then. Or just always check master? I'd say its rare enough that things break. The issue with that is that it's hard to determine if an update available without requesting the whole file because the version is the same, hmm.

**Comment by Mottie** [comment]
Well, I was thinking we could use the commits API

https://api.github.com/repos/StylishThemes/GitHub-Dark/commits

And look at the date of the last commit, but then we'd have to save the commit date instead of the version.

**Comment by Mottie** [comment]
I just went ahead and got rid of the dev setting... the userscript now grabs files from rawgit cdn (they claim [no limitations](https://rawgit.com/)), and it appears to update relatively quickly.

**Comment by Mottie** [comment]
Nevermind, rawgit cdn only updates once per url... switching back to the original urls.
