### ISSUE TITLE
No option to enable

### ISSUE THREAD

**Issue by Merrit** [StylishThemes/GitHub-Dark-Script#50]
I get no option to enable:

![github](https://user-images.githubusercontent.com/9575627/42452648-a866eaea-8358-11e8-9871-94403c1194fc.png)

I installed into Violentmonkey from Github:

![image](https://user-images.githubusercontent.com/9575627/42452611-8c062280-8358-11e8-92c4-539550bba82f.png)

g, 0  && g, - have no effect that I can see.

Window 10 x64 1803
Firefox x64 61.0.1

**Comment by Mottie** [comment]
Hi @Merrit!

Please make sure the userscript is enabled, you can verify it is by opening the developer tools (<kbd>F12</kbd>) console tab. You should see something like this:

![](https://user-images.githubusercontent.com/136959/42453015-329b591a-8351-11e8-978b-d0fe71cbec15.png)

If not, see if there are any errors reported in the console and share them here.

**Comment by Merrit** [comment]
Hi @Mottie!

Thanks for the reply.
It is definitely enabled as a userscript.

It is throwing errors it seems. To be safe I disabled adblocker & Privacy Badger, but that made no difference.

```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: !function e(a){var b=document.querySelec.... 50:1
Content Security Policy: The page’s settings blocked the loading of a resource at chrome-extension://17216d91-8546-48a0-b10f-69cca74b9e62/fonts/GothamSSm-Medium-Italic.woff (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at chrome-extension://17216d91-8546-48a0-b10f-69cca74b9e62/fonts/GothamSSm-Medium.woff (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at chrome-extension://17216d91-8546-48a0-b10f-69cca74b9e62/fonts/GothamSSm-Bold-Italic.woff (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at chrome-extension://17216d91-8546-48a0-b10f-69cca74b9e62/fonts/GothamSSm-Bold.woff (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at chrome-extension://17216d91-8546-48a0-b10f-69cca74b9e62/fonts/caecilialtstd-bold-webfont.woff (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at chrome-extension://17216d91-8546-48a0-b10f-69cca74b9e62/fonts/caecilialtstd-roman-webfont.woff (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at chrome-extension://17216d91-8546-48a0-b10f-69cca74b9e62/fonts/GothamSSm-Light-Italic.woff (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at chrome-extension://17216d91-8546-48a0-b10f-69cca74b9e62/fonts/GothamSSm-Light.woff (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at chrome-extension://17216d91-8546-48a0-b10f-69cca74b9e62/fonts/GothamSSm-Book-Italic.woff (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at chrome-extension://17216d91-8546-48a0-b10f-69cca74b9e62/fonts/GothamSSm-Book.woff (“font-src”). 
```

![image](https://user-images.githubusercontent.com/9575627/42453545-1274b7e4-835b-11e8-88e2-7ecd5f0cb888.png)

**Comment by Mottie** [comment]
Those errors are not related to this userscript. Try disabling that chrome extension that is attempting to load a custom font on GitHub and see if that was the cause.

**Comment by Merrit** [comment]
I disabled all extensions except for Violentmonkey, still wasn't working.

So I tried disabling Violentmonkey and installed Greasemonkey & the script again. That worked.

So it just seems like Violentmonkey isn't playing nicely.

Thanks for the help! 😃 🎆
