### ISSUE TITLE
GitHub removed jQuery

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark-Script#52]
See https://githubengineering.com/removing-jquery-from-github-frontend/

Github has dropped jQuery and `window.jQuery` and `window.$` currently are undefined. To my surprise, our script still seems to run.

I think we should update our jQuery usage to native DOM methods, should be pretty simple.

**Comment by Mottie** [comment]
That should already be done...

**Comment by Mottie** [comment]
The code looks like it's using jQuery because of these functions:

```js
function $(str, el) {
  return (el || document).querySelector(str);
}

function $(str, el) {
  return Array.from((el || document).querySelectorAll(str));
}
```

**Comment by silverwind** [comment]
Uh, nevermind then, I totally forgot that we had our own `$`, sorry.
