### ISSUE TITLE
Violentmonkey new metadata @inject-into for CSP restricted pages

### ISSUE THREAD

**Issue by zmni** [StylishThemes/GitHub-Dark-Script#53]
Details: https://violentmonkey.github.io/2018/11/23/inject-into-context/

**Comment by silverwind** [comment]
Thanks for the pointer. Sounds like we want to use `@inject-into content` or `@inject-into auto` to circumvent CSP. Drawback is no access to the page's own JS objects, but we don't need those, as far as I'm aware.
