### ISSUE TITLE
PR/Issue titles no longer dark

### ISSUE THREAD

**Issue by RedSparr0w** [StylishThemes/GitHub-Dark-Script#54]
When viewing an Issue/PR the title has a white background.

![image](https://user-images.githubusercontent.com/7288322/49608774-679aae80-f9fe-11e8-89e9-bcb1b7fced01.png)

**Comment by paulclarkaranz** [comment]
Forcing an update should now fix it: https://github.com/StylishThemes/GitHub-Dark/commit/acc76270b620027e7e4adeb98421305b00b1278b

**Comment by xt0rted** [comment]
As @paulclarkaranz said this was fixed earlier today. Forcing an update should fix the issue for you.
