### ISSUE TITLE
Mac OS safari issues

### ISSUE THREAD

**Issue by nkostoulas** [StylishThemes/GitHub-Dark-Script#57]
anyone having issues with safari on Mac OS? 

I've followed this https://github.com/StylishThemes/GitHub-Dark-Script/wiki/Install but no luck.

Mac OS high Sierra
safari 11.1.2

**Comment by silverwind** [comment]
Safari is applying GitHub's CSP rules to extensions which in turn block the style from loading. There is nothing we can do about it unfortunately. Also see:

https://github.com/Tampermonkey/tampermonkey/issues/296
https://github.com/StylishThemes/GitHub-Dark-Script/issues/13
https://bugs.webkit.org/show_bug.cgi?id=149000

I marked Safari as currently not working on the wiki.

**Comment by Mottie** [comment]
Also see https://github.com/StylishThemes/GitHub-Dark/issues/808.
