### ISSUE TITLE
Syntax themes are not working

### ISSUE THREAD

**Issue by nickforddev** [StylishThemes/GitHub-Dark-Script#61]
It looks like the styles do get applied but in such a way that the default colors for Twlight always take precedence:

![screen shot 2019-03-01 at 2 12 56 pm](https://user-images.githubusercontent.com/1086884/53660593-37912f00-3c2c-11e9-808b-a11155d3cf5a.png)

* **Browser**: Chrome - Version 72.0.3626.119 (Official Build) (64-bit)
* **Operating System**: MacOS - Mojave 10.14
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark-Script/blob/master/github-dark-script.user.js
* **Screenshot**: 
![screen shot 2019-03-01 at 2 11 46 pm](https://user-images.githubusercontent.com/1086884/53660483-fac53800-3c2b-11e9-8e6d-cbcc6f68d4b9.png)

**Comment by mallowigi** [comment]
Already fixed by https://github.com/StylishThemes/GitHub-Dark-Script/pull/59

**Comment by silverwind** [comment]
Should be fixed in 2.5.1.

**Comment by nickforddev** [comment]
🎉 Thank you!
