### ISSUE TITLE
Gruntfile change breaks script on Firefox

### ISSUE THREAD

**Issue by DarthParametric** [StylishThemes/GitHub-Dark-Script#62]
The [53d90e2 commit](https://github.com/StylishThemes/GitHub-Dark-Script/commit/53d90e2e1f5132e62776a95eaea299860996106d#diff-63e2ef08fcca315f0da7e1f7c6fcd9b7), changing line 481 from

`.replace(/\s+\/\* grunt build - remove to end of file(.*(\n|\r))+\}$/m, "");`

to

`.replace(/\s+\/\* grunt build - remove start \*\/.*\s+\/\* grunt build - remove end \*\/$/sm, "");`

results in the script no longer working on Firefox 65.0.2 on Windows using either Tampermonkey or Violentmonkey. Reverting to an older version or editing the line manually restores functionality.

**Comment by darcien** [comment]
Yeah, the `s` flag is not supported yet by Firefox. And it's unassigned on bugzilla [0].

Ref:
[0] https://bugzilla.mozilla.org/show_bug.cgi?id=1361856

**Comment by Mottie** [comment]
Hi @DarthParametric & @darcien!

Thanks for letting us know. It should be fixed now.

**Comment by DarthParametric** [comment]
~~Nope, still broken.~~

**Comment by Mottie** [comment]
Hmm, well maybe someone else can take a look. I've got to run 😞

**Comment by DarthParametric** [comment]
Sorry, my mistake., Disregard. It updated to the previous commit. Had to force a new manual update to get it to 2.5.2. It is working now.
