### ISSUE TITLE
Script settings button does not show

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark-Script#67]
Not sure when this broke but I can't see the settings menu in the user menu button in at least https://github.com/StylishThemes/GitHub-Dark-Script/commit/25d4c3f3e08fb73c7d79d393edddbd20ff8fdc0e or earlier:

<img width="263" src="https://user-images.githubusercontent.com/115237/60804232-54f77c00-a17d-11e9-8599-b40ee2ea77f7.png">

**Comment by Mottie** [comment]
Hmm, I'm seeing the entry in Chrome.

**Comment by silverwind** [comment]
Hmm, something Firefox specific?

**Comment by Mottie** [comment]
It looks that way.

In my custom nav userscript, I use this selector to target the dropdown, and it works in both:

```css
.Header .dropdown-item[href='/settings/profile'],
.Header .dropdown-item[data-ga-click*='go to profile'],
.js-header-wrapper .dropdown-item[href='/settings/profile'],
.js-header-wrapper .dropdown-item[data-ga-click*='go to profile']
```

**Comment by Mottie** [comment]
It wasn't the selector. It should be fixed now. I didn't bump the version in case you had other changes planned.

**Comment by silverwind** [comment]
Whoops, my bad. For some reason I assumed `for .. of` works just like `for .. in` without the guard for own properties, but this case proves it doesn't. Will bump the version.

**Comment by silverwind** [comment]
Today I learned:

```` js
> for (const k in {a: 1}) console.log(k)
a
> for (const k of {a: 1}) console.log(k)
Thrown:
TypeError: {(intermediate value)} is not iterable
````
