### ISSUE TITLE
Jupyter notebook stays black when script is disabled

### ISSUE THREAD

**Issue by veliona** [StylishThemes/GitHub-Dark-Script#68]
Hi,
I found the reproducible issue that happens while browsing with DarkScript toggled off on Jupyter notebooks. Even if the DarkScript is off, Jupyter Notebooks remain themed in black. 
Might be related to #56 

* **Browser**: Google Chrome v 75.0.3770.142 (Official Build) (64-bit)
* **Operating System**: MacOS v 10.14.5 (18F132)
* **Link to page with the issue**: https://github.com/veliona/Alppaka/blob/master/Alppaka.ipynb
* **Screenshots**:

![Screenshot 2019-08-15 at 09 03 49](https://user-images.githubusercontent.com/38378975/63078430-bc060e80-bf3b-11e9-97ed-462e08827a45.png)
![Screenshot 2019-08-15 at 09 04 01](https://user-images.githubusercontent.com/38378975/63078439-c3c5b300-bf3b-11e9-941d-690d9e8da5bd.png)

**Comment by Mottie** [comment]
Hi @veliona!

Hmm, that's going to be a troublesome, or nearly impossible, fix.

To apply the style, we have two separate userscripts running on `github.com` and the iframe of `render.githubusercontent.com`. Since the iframe is on a different domain, there isn't any way to perform cross-domain communication.

**Comment by Mottie** [comment]
If you *really* need to constantly enable/disable the style, then I would suggest switching to use [Stylus](https://github.com/openstyles/stylus) and our [GitHub userstyle](https://github.com/StylishThemes/GitHub-Dark).

**Comment by veliona** [comment]
Thank you for your response @Mottie! :)

Feel free to close the issue if you think that it's not worth the trouble and thanks for the suggestion.

**Comment by silverwind** [comment]
Yes, I think this is unsolvable via regular means. There *are* ways to communicate with an `<iframe>` but to my understanding, if said `<iframe>` is properly sandboxed, these methods will not work. So yeah, you would have to use the userstyle version to fix this (or simply reload the page).
