### ISSUE TITLE
Text box to paste style update

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark-Script#7]
Developing with the script is kind of hard when you can't update the CSS on the fly. We could add a text box to paste the CSS.This could be done with a single-line `<input>` with the `paste` event bound. To avoid issues, I usually use a small timeout like this:

``` js
$('input').on('paste', function(e) {
  setTimeout(function() {
    updateStyle(e.target.value);
  }, 100);
});
```

**Comment by Mottie** [comment]
Sounds good... I have been switching back-and-forth to test stuff with stylish LOL

I wonder though, should it be added when in "development" mode, or something? Because not everyone is going to use it.

**Comment by silverwind** [comment]
I'll think about something, I'll do an overhaul of the options menu soon, got a few changes in mind.

**Comment by Mottie** [comment]
Ok, I added this feature, and it appears to work LOL...

I dropped the "beta" in the version because the tag in the readme wasn't updating, but now Greasyfork is asking if I want to downgrade... LOL oh well.

**Comment by silverwind** [comment]
Nice! By the way, we should probably point `updateURL` and `downloadURL` to Greasyfork now.

**Comment by Mottie** [comment]
Greasyfork doesn't update as quickly LOL

**Comment by silverwind** [comment]
Ok, let's keep it on GitHub then. Maybe add a link to GreasyFork in the Readme.

**Comment by Mottie** [comment]
It's in the title.

**Comment by silverwind** [comment]
How's the textarea supposed to work? Paste the style and hit force update?

**Comment by Mottie** [comment]
yep... the placeholder text sorta explains it... I also added some [wiki docs](https://github.com/StylishThemes/GitHub-Dark-Script/wiki#force-update).

**Comment by Mottie** [comment]
Hmm, I think I missed a `return false` when clicking on the dropup menu icon.

**Comment by silverwind** [comment]
Hmm, it's a bit non-intuitive, let me try that `paste` event.

**Comment by Mottie** [comment]
Ok, could you add that `return false` then? After [line 712](https://github.com/StylishThemes/GitHub-Dark-Script/blob/master/github-dark-script.user.js#L712).

And please feel free to make whatever mods you want... I gotta run now!

**Comment by silverwind** [comment]
Done! One could even go as far as hide the options after a force update.

**Comment by Mottie** [comment]
Hmm, every time I open the panel, it automatically opens the textarea... then once I paste something, I can't use the toggle button any more.

**Comment by silverwind** [comment]
Should be fixed, thanks.
