### ISSUE TITLE
Dark discussion font color

### ISSUE THREAD

**Issue by MichalLytek** [StylishThemes/GitHub-Dark-Script#70]
* **Browser**: Opera 63
* **Operating System**: 
Windows 10
* **Link to page with the issue**: 
https://github.com/MichalLytek/type-graphql/pull/415
* **Screenshot**:
![image](https://user-images.githubusercontent.com/10618781/64475082-20547080-d17e-11e9-826c-60f66832a04a.png)

The color comes from this:
![image](https://user-images.githubusercontent.com/10618781/64475096-47ab3d80-d17e-11e9-8c71-a43f806c7601.png)

And overwrite the `!important` 😞

**Comment by the-j0k3r** [comment]
@MichalLytek This has been fixed in GitHub Dark already, so update your local copy.

See https://github.com/StylishThemes/GitHub-Dark/issues/993 and fix https://github.com/StylishThemes/GitHub-Dark/commit/e67cb73b4500993b8b4ae9a9a9ef6f7ae0f9ba58

**Comment by MichalLytek** [comment]
I've tried to update the script first but without luck:

![image](https://user-images.githubusercontent.com/10618781/64475148-0a937b00-d17f-11e9-86ea-b0ecea3b6f89.png)

I used this url:
`https://greasyfork.org/scripts/15562-github-dark-script/code/GitHub%20Dark%20Script.user.js`

Changed to github:
`https://raw.githubusercontent.com/StylishThemes/GitHub-Dark-Script/master/github-dark-script.user.js`

Thanks! 😉

**Comment by the-j0k3r** [comment]
I havent used the GHD script version but

![settings](https://cloud.githubusercontent.com/assets/136959/22908590/022f56d8-f215-11e6-954c-decc9ecbd259.png)

That force update style button is what you should press to update, I dont think its necessary to change URL's See the wiki entry https://github.com/StylishThemes/GitHub-Dark-Script/wiki#force-update

Essentially you want to update the style the script loads, not the script itself, which is what you are trying to do.

**Comment by the-j0k3r** [comment]
You can also not use the script version and instead install Stylus and the GHD theme, same update interval but also more possibilities because you can add more themes from other sites.

See https://github.com/StylishThemes/GitHub-Dark#installation
