### ISSUE TITLE
Github page gets stuck during loading

### ISSUE THREAD

**Issue by and3rson** [StylishThemes/GitHub-Dark-Script#72]
* **Browser**: Mozilla Firefox 69.0b7, ViolentMonkey
* **Operating System**: Arch Linux rolling
* **Link to page with the issue**: https://github.com/

Since this morning Github fails to load if this script is enabled. After some time, there's a notification that a script is stuck and offers to terminate it or start debug. Unfortunately hitting "debug" button just opens a debugger with no additional information about current stack trace.

**Comment by redkite** [comment]
Can confirm, same issue with Firefox 70.0.1 on Ubuntu LTS 18.04.

Reliably freezes the browser and/or the whole machine.

**Comment by unixfox** [comment]
Can confirm same issue on Firefox and on Chromium with ViolentMonkey.

**Comment by Mottie** [comment]
I'm not seeing any issues on my Windows 10 machine, Tampermonkey v4.9.5941 & Firefox 70.0.1.

I don't think it'd be related to the Linux OS, so it might be associated with ViolentMonkey or maybe interference from another extension. Please try disabling other extensions to see if it's a combination causing the problem.

**Comment by the-j0k3r** [comment]
> Since this morning

Arch Linux bleeding edge, cant say Im surprised. What Other OS's can you test in?

**Comment by unixfox** [comment]
You are right @Mottie, it's related to ViolentMonkey. I just tested on Tampermonkey and it's working perfectly.

**Comment by KaKi87** [comment]
Can confirm this issue happens when using ViolentMonkey but not Tampermonkey.

[ViolentMonkey's latest version was released 8 hours ago](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.12.0).

**Comment by tophf** [comment]
While this is indeed a bug in Violentmonkey added by yours truly, a quick workaround is to replace `GM.addStyle(` call with `GM_addStyle(`. The latter can be used safely as it's added if not present by gm4-polyfill.js. Moreover there is no such thing as GM.addStyle in [Greasemonkey4 API](https://wiki.greasespot.net/Greasemonkey_Manual:API).

**Comment by maricn** [comment]
Updating Violentmonkey to latest version fixes the issue - https://github.com/violentmonkey/violentmonkey/releases/tag/v2.12.1

**Comment by KaKi87** [comment]
This issue has been resolved and should be closed now. Thanks
