### ISSUE TITLE
toggle monospace button

### ISSUE THREAD

**Issue by boneskull** [StylishThemes/GitHub-Dark-Script#8]
Moved from [here](/StylishThemes/GitHub-Dark/issues/285).

I think adding a toggle for monospace `textarea` fields would be cool.  Some users could really use the monospace font; others don't need it.

**Comment by Mottie** [comment]
What do you think of this cruddy icon I made?

![2016-02-04 19_50_07-suggestion_ monospace input fields issue 285 stylishthemes_github-dark](https://cloud.githubusercontent.com/assets/136959/12835757/8de49cf2-cb78-11e5-8b4c-ac40d64ca3c6.png)

**Comment by Mottie** [comment]
I wasn't sure if it was necessary to add a panel option to allow applying the monospaced font by default.

What do you all think of the icon? I'm sure it can be improved.

**Comment by Mottie** [comment]
Oh, and make sure to "Force Update Style" to get the latest GHD style... I added a definition to make the monospaced icon show the base color when active.

**Comment by boneskull** [comment]
Something like this _might_ be more clear, but I don't know.

![0](https://cloud.githubusercontent.com/assets/924465/12859468/2ddb21c6-cc0b-11e5-91dc-c9e8586ed058.png)

**Comment by boneskull** [comment]
Given fontawesome has no relevant icon, such a thing must not exist. :smile:

**Comment by silverwind** [comment]
Here's my suggestion:

![tags](https://cloud.githubusercontent.com/assets/115237/12859991/fb152c9c-cc59-11e5-82f9-07be72e96d6c.png)

``` svg
<svg xmlns="http://www.w3.org/2000/svg" width="640" height="512" viewBox="0 0 640 512"><path d="M416 368l48 48 160-160L464 96l-48 48 112 112zM224 144l-48-48L16 256l160 160 48-48-112-112zM350.65 75.26l34.733 9.472-95.993 352.013-34.734-9.472L350.65 75.26z"/></svg>
```

**Comment by Mottie** [comment]
With that icon, I think people will think it makes a code block.

**Comment by silverwind** [comment]
Yeah it's a bad choice given there's a similar icon already there. Might have to dig through [icomoon](https://icomoon.io/app/#/select) some more.

**Comment by Mottie** [comment]
What about this one?

![2016-02-05 16_19_47-toggle-font svg](https://cloud.githubusercontent.com/assets/136959/12860760/597ca0e8-cc24-11e5-9fe6-9ccf66d946fe.png)

This is what it looks like in place

![2016-02-05 16_21_08-toggle monospace button issue 8 stylishthemes_github-dark-script](https://cloud.githubusercontent.com/assets/136959/12860783/84263a84-cc24-11e5-90e3-6d950fafca84.png)

``` html
<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 16 16">
  <path d="M2.92 6.14v3.53c0 0.27 0.02 0.46 0.06 0.55 0.04 0.09 0.1 0.16 0.18 0.2 0.08 0.05 0.22 0.07 0.43 0.07v0.17H1.46v-0.17c0.21 0 0.36-0.02 0.43-0.06 0.07-0.04 0.13-0.11 0.18-0.21s0.07-0.28 0.07-0.55V7.98c0-0.48-0.01-0.78-0.04-0.92C2.06 6.95 2.03 6.88 1.98 6.84s-0.11-0.06-0.2-0.06c-0.09 0-0.2 0.02-0.33 0.07L1.39 6.68l1.32-0.54H2.92zM2.52 3.85c0.13 0 0.25 0.05 0.34 0.14s0.14 0.21 0.14 0.34 -0.05 0.25-0.14 0.35C2.77 4.77 2.66 4.82 2.52 4.82s-0.25-0.05-0.34-0.14C2.08 4.58 2.04 4.47 2.04 4.33s0.05-0.25 0.14-0.34S2.39 3.85 2.52 3.85z"/>
  <path d="M12.59 6.67H11.17v-0.69h2.27v4.12h1.43v0.7h-3.86v-0.69h1.58V6.67zM12.89 3.96c0.09 0 0.18 0.02 0.26 0.05 0.08 0.03 0.15 0.08 0.21 0.14 0.06 0.06 0.11 0.13 0.14 0.21 0.03 0.08 0.05 0.16 0.05 0.26 0 0.09-0.02 0.17-0.05 0.25 -0.03 0.08-0.08 0.15-0.14 0.21 -0.06 0.06-0.13 0.11-0.21 0.14 -0.08 0.03-0.17 0.05-0.26 0.05 -0.09 0-0.18-0.02-0.26-0.05 -0.08-0.03-0.15-0.08-0.21-0.14 -0.06-0.06-0.1-0.13-0.14-0.21 -0.03-0.08-0.05-0.16-0.05-0.25 0-0.09 0.02-0.18 0.05-0.26 0.03-0.08 0.08-0.15 0.14-0.21 0.06-0.06 0.13-0.11 0.21-0.14S12.79 3.96 12.89 3.96z"/>
  <path d="M10.04 8.2v0.22C9.86 8.56 9.69 8.74 9.52 8.98c-0.17 0.23-0.37 0.59-0.62 1.06H8.68c0.13-0.55 0.31-1.05 0.54-1.49h-3.65c0.23 0.44 0.41 0.94 0.54 1.49H5.89c-0.24-0.47-0.45-0.83-0.62-1.06C5.1 8.74 4.93 8.56 4.76 8.42V8.2c0.18-0.14 0.35-0.33 0.52-0.56 0.17-0.23 0.38-0.58 0.62-1.06h0.22c-0.13 0.55-0.31 1.05-0.54 1.49h3.65C8.99 7.63 8.81 7.13 8.68 6.58h0.22c0.24 0.48 0.45 0.83 0.62 1.06C9.69 7.88 9.86 8.06 10.04 8.2z"/>
</svg>
```

**Comment by silverwind** [comment]
Not bad. Could replace the arrow with a slash, the arrows are kind of hard to read at that size.

**Comment by Mottie** [comment]
Ok, which looks better?

Thicker arrow
![2016-02-05 17_47_13-toggle monospace button issue 8 stylishthemes_github-dark-script](https://cloud.githubusercontent.com/assets/136959/12862364/92c7784e-cc30-11e5-963a-7d7e84f6cf84.png)

Standard slash
![2016-02-05 17_27_27-toggle monospace button issue 8 stylishthemes_github-dark-script](https://cloud.githubusercontent.com/assets/136959/12862105/01ebacb6-cc2e-11e5-9aeb-9cb7c4137322.png)

Big slash
![2016-02-05 17_28_50-toggle monospace button issue 8 stylishthemes_github-dark-script](https://cloud.githubusercontent.com/assets/136959/12862106/05d6dcce-cc2e-11e5-8428-9a384d66917b.png)

**Comment by silverwind** [comment]
Big slash with slightly more spacing around the slash :)

**Comment by Mottie** [comment]
I'm not sure this is any better... I'd have to shrink the two i's even more.

![2016-02-05 18_09_36-toggle monospace button issue 8 stylishthemes_github-dark-script](https://cloud.githubusercontent.com/assets/136959/12862720/c30d9850-cc33-11e5-8e3b-786932c249d2.png)

Here, I'll let you mess with it:

``` html
<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 32 32">
  <path d="M6.66 7.46v8.41c0 0.66 0.05 1.09 0.14 1.31 0.09 0.21 0.23 0.37 0.41 0.48 0.18 0.11 0.52 0.16 1.02 0.16v0.41h-5.07v-0.41c0.5 0 0.86-0.05 1.03-0.14 0.16-0.11 0.3-0.27 0.41-0.5 0.11-0.23 0.16-0.66 0.16-1.3v-4.03c0-1.14-0.04-1.87-0.11-2.2C4.61 9.39 4.52 9.23 4.41 9.12 4.3 9.02 4.14 8.98 3.95 8.98c-0.21 0-0.48 0.05-0.77 0.18L3 8.75l3.14-1.28H6.66zM5.71 2c0.32 0 0.59 0.11 0.82 0.34 0.23 0.23 0.34 0.5 0.34 0.82 0 0.32-0.11 0.59-0.34 0.82C6.3 4.2 6.02 4.32 5.71 4.32c-0.32 0-0.59-0.11-0.82-0.34s-0.36-0.5-0.36-0.82c0-0.32 0.11-0.59 0.34-0.82C5.11 2.11 5.38 2 5.71 2z"/>
  <path d="M24.07 20.18h-3.39v-1.64h5.39v9.8H29.5V30h-9.18v-1.66h3.77v-8.16H24.07zM24.77 13.74c0.21 0 0.43 0.04 0.63 0.13 0.18 0.09 0.36 0.2 0.5 0.34s0.25 0.3 0.34 0.5c0.07 0.18 0.13 0.39 0.13 0.61 0 0.22-0.04 0.41-0.13 0.61 -0.09 0.2-0.19 0.36-0.34 0.5s-0.3 0.25-0.5 0.32c-0.2 0.09-0.39 0.13-0.62 0.13 -0.21 0-0.43-0.04-0.61-0.12 -0.19-0.07-0.35-0.19-0.5-0.34 -0.14-0.14-0.25-0.3-0.34-0.5 -0.07-0.2-0.13-0.39-0.13-0.61s0.04-0.43 0.13-0.61c0.07-0.18 0.2-0.36 0.34-0.5 0.14-0.14 0.31-0.25 0.5-0.34C24.34 13.77 24.56 13.74 24.77 13.74z"/>
  <path d="M2 30L27.82 2H30L4.14 30H2z"/>
</svg>
```

Don't forget my screenshots are of a 110% zoomed page :grin:

**Comment by silverwind** [comment]
Moved those i's slightly apart and ran it through [svgomg](https://jakearchibald.github.io/svgomg/):

``` svg
<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32">
  <path d="M6.285 7.385v8.41c0 .66.05 1.09.14 1.31.09.21.23.37.41.48.18.11.52.16 1.02.16v.41h-5.07v-.41c.5 0 .86-.05 1.03-.14.16-.11.3-.27.41-.5.11-.23.16-.66.16-1.3v-4.03c0-1.14-.04-1.87-.11-2.2-.04-.26-.13-.42-.24-.53-.11-.1-.27-.14-.46-.14-.21 0-.48.05-.77.18l-.18-.41 3.14-1.28h.52v-.01zm-.95-5.46c.32 0 .59.11.82.34.23.23.34.5.34.82 0 .32-.11.59-.34.82-.23.22-.51.34-.82.34-.32 0-.59-.11-.82-.34s-.36-.5-.36-.82c0-.32.11-.59.34-.82.24-.23.51-.34.84-.34zm18.81 18.18h-3.39v-1.64h5.39v9.8h3.43v1.66h-9.18v-1.66h3.77v-8.16h-.02zm.7-6.44c.21 0 .43.04.63.13.18.09.36.2.5.34s.25.3.34.5c.07.18.13.39.13.61 0 .22-.04.41-.13.61s-.19.36-.34.5-.3.25-.5.32c-.2.09-.39.13-.62.13-.21 0-.43-.04-.61-.12-.19-.07-.35-.19-.5-.34-.14-.14-.25-.3-.34-.5-.07-.2-.13-.39-.13-.61s.04-.43.13-.61c.07-.18.2-.36.34-.5s.31-.25.5-.34c.17-.09.39-.12.6-.12zM2 30L27.82 2H30L4.14 30H2z"/>
</svg>
```

**Comment by silverwind** [comment]
update:

![f3](https://cloud.githubusercontent.com/assets/115237/12862988/d335f99c-cc70-11e5-9ee0-d44f37b0d692.png)

``` svg
<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32">
  <path d="M5.91 7.31v8.41c0 .66.05 1.09.14 1.31.09.21.23.37.41.48.18.11.52.16 1.02.16v.41H2.41v-.41c.5 0 .86-.05 1.03-.14.16-.11.3-.27.41-.5.11-.23.16-.66.16-1.3V11.7c0-1.14-.04-1.87-.11-2.2-.04-.26-.13-.42-.24-.53-.11-.1-.27-.14-.46-.14-.21 0-.48.05-.77.18l-.18-.41 3.14-1.28h.52v-.01zm-.95-5.46c.32 0 .59.11.82.34.23.23.34.5.34.82 0 .32-.11.59-.34.82-.23.22-.51.34-.82.34-.32 0-.59-.11-.82-.34s-.36-.5-.36-.82c0-.32.11-.59.34-.82.24-.23.51-.34.84-.34zm19.636 19.006h-3.39v-1.64h5.39v9.8h3.43v1.66h-9.18v-1.66h3.77v-8.16h-.02zm.7-6.44c.21 0 .43.04.63.13.18.09.36.2.5.34s.25.3.34.5c.07.18.13.39.13.61 0 .22-.04.41-.13.61s-.19.36-.34.5-.3.25-.5.32c-.2.09-.39.13-.62.13-.21 0-.43-.04-.61-.12-.19-.07-.35-.19-.5-.34-.14-.14-.25-.3-.34-.5-.07-.2-.13-.39-.13-.61s.04-.43.13-.61c.07-.18.2-.36.34-.5s.31-.25.5-.34c.17-.09.39-.12.6-.12zM2 30L27.82 2H30L4.14 30H2z"/>
</svg>
```

**Comment by Mottie** [comment]
Oooo, I like that svgomg!

Ok, I did have to change the width & height to 18 so that it matches the size of the other icons... tell me what you think.

**Comment by silverwind** [comment]
Looks great and works, nice!

**Comment by Mottie** [comment]
Awesome :grin:

**Comment by boneskull** [comment]
thanks guys
