### ISSUE TITLE
theme need to update

### ISSUE THREAD

**Issue by bluelovers** [StylishThemes/GitHub-Dark-Script#81]
![image](https://user-images.githubusercontent.com/167966/85193112-ef51c080-b2f7-11ea-9909-601249c26633.png)

![image](https://user-images.githubusercontent.com/167966/85193115-f8db2880-b2f7-11ea-9cb8-217d9d840084.png)

![image](https://user-images.githubusercontent.com/167966/85193131-3e97f100-b2f8-11ea-872b-69f223fb2e25.png)

* **Browser**: 
* **Operating System**: 
* **Link to page with the issue**: 
* **Screenshot**:

**Comment by silverwind** [comment]
See https://github.com/StylishThemes/GitHub-Dark/issues/1123. Your options are to install the userstyle linked there or disable the "design update" feature preview in GitHub's menu.
