### ISSUE TITLE
fails to add button to profile

### ISSUE THREAD

**Issue by boneskull** [StylishThemes/GitHub-Dark-Script#9]
```
Uncaught TypeError: this.data.version.match is not a function
  ghd.buildSettings @ VM2209:460
  (anonymous function) @ VM2209:769
  i @ VM2209:7
  j.fireWith @ VM2209:7
  n.extend.ready @ VM2209:7
  J @ VM2209:7
  q @ VM2208:52
```

TamperMonkey v3.12.58, latest Chrome on MacOS X

**Comment by silverwind** [comment]
There's also some linter errors around these parts:

```
  449:58  error  "i" is defined but never used  no-unused-vars
  450:22  error  Redundant radix parameter      radix
```

@Mottie you can run the linter now with `npm run lint` after a `npm i` :wink:

**Comment by Mottie** [comment]
:cry: I like my redundant radix parameter.

**Comment by silverwind** [comment]
Hmm yeah let me change the rules.

**Comment by Mottie** [comment]
LOL, I was kidding.

**Comment by silverwind** [comment]
Alright :laughing: Care to take a look at the issue here?

**Comment by Mottie** [comment]
I won't be able to get to look at it until a little later tonight.

**Comment by silverwind** [comment]
I think the issue is about `this.data.version` defaulting to a Number type, which of course has no `.match`, but I'll let you fix it, not so sure around these parts ;)
